// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type Mutation struct {
}

type PantryEntryInput struct {
	Name         string  `json:"name"`
	Quantity     *int    `json:"quantity,omitempty"`
	QuantityType *string `json:"quantityType,omitempty"`
}

type Query struct {
}

type UserRegisterInput struct {
	Name     *string `json:"name,omitempty"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}
