// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type Mutation struct {
}

type PantryEntryInput struct {
	Name         string   `json:"name"`
	Quantity     *float64 `json:"quantity,omitempty"`
	QuantityType *string  `json:"quantityType,omitempty"`
}

type Query struct {
}

type UserRegisterInput struct {
	Name      *string `json:"name,omitempty"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Password  string  `json:"password"`
}
