services:
  db:
    image: mongo:latest
    container_name: pantry_mongodb
    environment:
      MONGO_INITDB_DATABASE: pantry_butler
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=db
    depends_on:
      - db
  envoy:
    image: envoyproxy/envoy:v1.35.0
    container_name: envoy
    ports:
      - 8080:8080
    volumes:
      - ./config/envoy/conf.yaml:/etc/envoy/envoy.yaml

volumes:
  mongodb_data:
