version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pantry_butler_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # api:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - PORT=8080
  #     - DATABASE_URL=db
  #   depends_on:
  #     - db

volumes:
  postgres_data:
