// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PantryEntryInput struct {
	ID         *string `json:"id,omitempty"`
	Name       string  `json:"name"`
	Expiration *int    `json:"expiration,omitempty"`
	Quantity   *int    `json:"quantity,omitempty"`
}

type Query struct {
}

type RecipeInput struct {
	Ingredients []string `json:"ingredients"`
	Difficulty  int      `json:"difficulty"`
	Cuisine     string   `json:"cuisine"`
}

type Response struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}
