// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

import (
	"time"
)

type Mutation struct {
}

type PantryEntryInput struct {
	Name         string     `json:"name"`
	Expiration   *time.Time `json:"expiration,omitempty"`
	Quantity     *int       `json:"quantity,omitempty"`
	QuantityType *string    `json:"quantityType,omitempty"`
}

type Query struct {
}
